import type { Metadata } from "next";
 
import "./globals.css";
import { inter } from "@/lib/font";
import Navbar from "@/components/Navbar";
import Footer from "@/components/footer";

 


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body
        className={` antialiased`}
      >
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
